# Generated by Django 5.0 on 2024-11-08 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BarakatCRM', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Shoes',
            new_name='Product',
        ),
    ]
