# Generated by Django 5.0 on 2024-11-08 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BarakatCRM', '0002_rename_shoes_product'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SkladShoes',
            new_name='SkladProducts',
        ),
    ]
