# Generated by Django 5.0 on 2024-11-08 15:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BarakatCRM', '0003_rename_skladshoes_skladproducts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BarakatCRM.city'),
        ),
    ]
